### PR TITLE
fix: multiple calls to connect creates multiple (leaking) sockets

### PR DESCRIPTION
**Pull request by nicobritos**
* Check and return the `_connectionCompleter.future` when calling `connect` multiple times.
* Check if there is already a `_socketChannel` created before making a connection to avoid creating multiple leaking sockets.
* Cancel the StreamSubscription created when creating a socket after disconnecting.

### CODE REVIEW

**Comment by mcfugger** [comment]
This is a good observation. But it is not a fault of `WebSocketConnectionDelegate` - the delegates just does what you tell it to do - to connect, disconnect or reconnect (it must stay as abstract at this point). To avoid the leaks - it must be prevented by the higher structure `PusherChannelsClient`. But I will add StreamSubscription to `connect` method.

**Comment by mcfugger** [comment]
This is a good observation. But it is not a fault of `WebSocketConnectionDelegate` - the delegates just does what you tell it to do - to connect, disconnect or reconnect (it must stay as abstract at this point). To avoid the leaks - it must be prevented by the higher structure `PusherChannelsClient`. But I will add StreamSubscription to `connect` method.

**Comment by nicobritos** [comment]
Oh yeah you are right. Will modify this PR later with those changes!

**Comment by mcfugger** [comment]
@nicobritos  Closing with #11

**Pull request closed without merging**
